version: '3.8'

services:
  db:
    container_name: doc-read-hub_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    container_name: doc-read-hub_web
    build:
      context: .
      dockerfile: Dockerfile.dev  # Use Dockerfile.dev for building the image
    command: bash -c "while [ true ]; do sleep 10; done"
    volumes:
      - .:/doc-read-hub
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - db
