default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres

development:
  <<: *default
  database: pdf-book-reader_development


test:
  <<: *default
  database: pdf-book-reader_test
