default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("DB_HOST") { "db" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: doc-read-hub_rails_development

test:
  <<: *default
  database: doc-read-hub_rails_test

production:
  <<: *default
  database: doc-read-hub_rails_production